### ISSUE TITLE
 Watcher#initialize: The root_path argument must be an absolute path

### ISSUE THREAD

**Issue by agross** [ddfreyne/adsf#14]
On Windows (sorry) paths will not start with `/` but with e.g. `C:/`. Perhaps it's better to compare the output of `File.absolute_path(root_dir)` with `root_dir` and throw if they differ?

**Comment by ddfreyne** [comment]
Can you check whether https://github.com/ddfreyne/adsf/commit/ae278ec90bf389616e438b50347507d53aaab615 fixes the problem for you?

**Comment by ddfreyne** [comment]
(I don’t have a Windows machine to test on, unfortunately.)

**Comment by agross** [comment]
Works for me! 👍

**Comment by ddfreyne** [comment]
adsf-live 1.4.1 has the fix.
