### ISSUE TITLE
Basic authentication - out of scope?

### ISSUE THREAD

**Issue by DannyBen** [ddfreyne/adsf#21]
How out of scope would it be to consider adding basic auth support?

Ideally - I would love adsf to automatically detect if there is an `ADSF_AUTH` environment variable, and act accordingly, so we can run:

```
$ ADSF_AUTH=admin:p4ssw0rd adsf
```

Since this is Rack, I am guessing it should not be too difficult to add, like:

```ruby
if ENV['ADSF_AUTH']
  user, pass = ENV['ADSF_AUTH'].split ':'
  
  use Rack::Auth::Basic, "Protected Area" do |username, password|
    username == user && password == pass
  end
end
```

**Comment by ddfreyne** [comment]
Hey @DannyBen,

Authentication is out of scope for adsf — adsf is really intended to be an as-simple-as-possible web server for development/testing purposes.

You could [use adsf programmatically](https://github.com/ddfreyne/adsf#using-adsf-programmatically), and make use of `Rack::Auth::Basic` that way.

I‘ll close the GitHub issue now, but we can keep the conversation going!

**Comment by DannyBen** [comment]
I suspected as much. I saw the programmatic use, but am unsure what is the pattern to have a ruby script that runs ADSF and adds a rack middleware to it. The programmatic use section in the readme immediately talks about `IndexFileFinder` which is confusing... How would I go about running adsf from a ruby script after adding a rack middle ware of my choice?
