### ISSUE TITLE
Publish current version to rubygems.org

### ISSUE THREAD

**Issue by angelikatyborska** [ddfreyne/adsf#5]
When I installed your gem from rubygems.org and tried to run it, it crashed:

```
/Users/angelika/.rvm/gems/ruby-2.3.0/gems/adsf-1.2.0/bin/adsf:64:in `<top (required)>': uninitialized constant Rack::Handler::Mongrel (NameError)
	from /Users/angelika/.rvm/gems/ruby-2.3.0/bin/adsf:23:in `load'
	from /Users/angelika/.rvm/gems/ruby-2.3.0/bin/adsf:23:in `<main>'
	from /Users/angelika/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/angelika/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I had to clone the repo and build the gem myself, it's working now. I know it's not a big deal, but maybe you could publish the current version (without Mongrel dependency) to rubygems.org, so it's more convenient for people to install it.

**Comment by ddfreyne** [comment]
Sorry for dropping the ball on this! I’ve pushed 1.2.1, which should fix the problem you’re experiencing. Thanks for letting me know!
