### ISSUE TITLE
Getting `rack requires Ruby version >= 2.2.2.` on Ruby 2.0

### ISSUE THREAD

**Issue by Nakilon** [ddfreyne/adsf#8]
A Dead Simple server should probably be as much compatible as possible.

**Comment by Nakilon** [comment]
Solved by `gem install rack --version 1.6.0`

**Comment by ddfreyne** [comment]
Glad you got it solved!

FYI, Ruby 2.1 is unsupported, and 2.2 is in security maintenance. I recommend upgrading to at least Ruby 2.3.
