### ISSUE TITLE
Custom Headers?

### ISSUE THREAD

**Issue by shideneyu** [ddfreyne/adsf#9]
Hey. Thanks for your great job. I just wondered if it was possible to add a custom header ?

To prevent such exceptions like 

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Thanks

**Comment by ddfreyne** [comment]
Hi,

There’s currently no support for setting custom headers. I think that setting custom headers, or at least setting `Access-Control-Allow-Origin`, falls outside of the scope of adsf — as it’s mean to be a simple server for serving static assets for development purposes.

Can you share a bit more about what your setup is like and how `Access-Control-Allow-Origin` fits in?

**Comment by ddfreyne** [comment]
@shideneyu Can you describe in more detail what the use case is for you?

**Comment by shideneyu** [comment]
Hello @ddfreyne , sorry for the late answer.

Yes indeed. I wanted to use `adsf` to host a json file that can then be pulled by ajax by a client. But as that page requires a 'Access-Control-Allow-Origin' header, I simply can't do it with 'adsf'

I discovered your gem thanks [to this gist](https://gist.github.com/willurd/5720255)

So I needed another one liner to perform my deed. I am now using:

`http-server . --cors -p8000`


If you could add some options that `http-server` use ( [reference here](https://www.npmjs.com/package/http-server) ), it would be a nice addition for `asdf` ;)

Im my opinion the scope of a gem is not simply the basic usage, it should actually allow users to make a useful usage of it, thus allowing them to add more options. But good job anyways, nice gem.

**Comment by ddfreyne** [comment]
See #12 for a fix

**Comment by shideneyu** [comment]
Thank you !

**Comment by ddfreyne** [comment]
Released as adsf v1.3.1.
